import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavigation from '../app/components/side-nav'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><div className="sidebar  ">
      <div className="drawer lg:drawer-open">
        <input id="my-drawer-2" type="checkbox" className="drawer-toggle " />
        <div className="drawer-content bg-sidebar ">
          <div className=" flex bg-slate-100 items-center ">
            <label
              htmlFor="my-drawer-2"
              className=" cursor-pointer drawer-button pt-4 pl-3 lg:hidden"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5"
                fill="none"
                viewBox="0 0 28 28"
                stroke="#FF009E"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M4 6h16M4 12h16M4 18h7"
                />
              </svg>
            </label>
          </div>
          <div className=" flex flex-col bg-slate-100 py-10 lg:min-h-screen ">
            {children}
          </div>
        </div>
        <div className="drawer-side ">
          <label
            htmlFor="my-drawer-2"
            aria-label="close sidebar"
            className="drawer-overlay"
          ></label>
          <ul className="menu bg-white border-2 border-sidebar-border py-[10px] gap-14 lg:w-[20vw] flex flex-col min-h-full text-base-content">
            {/* Sidebar content here */}
            <SideNavigation />
          </ul>
        </div>
      </div>
    </div></body>
    </html>
  );
}
